services:
  backend:
    build: ./apps
    restart: always
    links:
      - db
    ports:
      - "80:3000"
    volumes:
      - app-data:/apps/public/images

  db:
    image: "mariadb"
    restart: always
    links:
      - phpmyadmin
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=training
      - MYSQL_USER=peserta
      - MYSQL_PASSWORD=password
    volumes:
      - /apps/database/.:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
  
  phpmyadmin:
    image: "phpmyadmin"
    restart: always
    ports:
      - "8000:80"


volumes:
  app-data:
  db-data:
  